server:
  port: 8080

spring:
  h2:
    console:
      enabled: 'true'
    datasource:
      platform: h2
      url: 'jdbc:h2:mem:sam'
      username: user
      password: pass
  application:
    name: SECURITY-SERVICE
  jpa:
    defer-datasource-initialization: 'true'