server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  h2:
    console:
      enabled: 'true'
  datasource:
    platform: h2
    url: 'jdbc:h2:mem:sam'
    username: user
    password: pass
  application:
    name: SECURITY-SERVICE

  jpa:
    defer-datasource-initialization: 'true'