spring:
  h2:
    console:
      enabled: 'true'
  datasource:
    platform: h2
    url: 'jdbc:h2:mem:sam'
    username: root
    password: password
  jpa:
    defer-datasource-initialization: 'true'

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false